project_name: srl-grpc-tunnel
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}-{{.ShortCommit}}
    goos:
      - linux
    goarch:
      - amd64
archives:
  - replacements:
      linux: Linux
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nfpms:
  - id: srl-grpc-tunnel
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      amd64: x86_64
      linux: Linux
    vendor: Nokia
    homepage: https://github.com/karimra/srl-grpc-tunnel
    maintainer: Karim Radhouani <karim.radhouani@nokia.com>
    description: gRPC tunnel application for Nokia SR Linux
    formats:
      - rpm
    license: "BSD 2"
    bindir: /opt/srlinux/usr/bin/
    contents:
      - src: ./yang/grpc-tunnel.yang
        dst: /opt/grpc-tunnel/yang/grpc-tunnel.yang
      - src: ./yaml/grpc-tunnel.yaml
        dst: /etc/opt/srlinux/appmgr/grpc-tunnel.yml
    overrides:
      rpm:
        scripts:
