project_name: srl-grpc-tunnel
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}-{{.ShortCommit}}
    goos:
      - linux
    goarch:
      - amd64
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nfpms:
  - id: srl-grpc-tunnel
    file_name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    vendor: Nokia
    homepage: https://github.com/karimra/srl-grpc-tunnel
    maintainer: Karim Radhouani <karim.radhouani@nokia.com>
    description: gRPC tunnel application for Nokia SR Linux
    formats:
      - rpm
    license: "BSD 2"
    bindir: /usr/local/bin/
    contents:
      - src: ./yang/grpc-tunnel.yang
        dst: /opt/grpc-tunnel/yang/grpc-tunnel.yang
      - src: ./yaml/grpc-tunnel.yaml
        dst: /etc/opt/srlinux/appmgr/grpc-tunnel.yml
    overrides:
      rpm:
        scripts: